### ISSUE TITLE
你这项目少模块，能不能解决下

### ISSUE THREAD

**Issue by wanliyunyan** [cobantou/build-a-react-boilerplate-from-beginning#1]
当我start 的时候报错，找不到好多模块

**Comment by wanliyunyan** [comment]
我把需要的模块都取的最新的还是报别的错误
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (D:\project\build-a-react-boilerplate-from-beginning-master\node_modules\_yargs@9.0.1@yargs\lib\argsert.js:65:9)
    at parsed.optional.forEach (D:\project\build-a-react-boilerplate-from-beginning-master\node_modules\_yargs@9.0.1@yargs\lib\argsert.js:47:39)
    at Array.forEach (<anonymous>)
    at argsert (D:\project\build-a-react-boilerplate-from-beginning-master\node_modules\_yargs@9.0.1@yargs\lib\argsert.js:42:21)
    at Object.version (D:\project\build-a-react-boilerplate-from-beginning-master\node_modules\_yargs@9.0.1@yargs\yargs.js:712:5)
    at Object.<anonymous> (D:\project\build-a-react-boilerplate-from-beginning-master\node_modules\_webpack-dev-server@2.9.1@webpack-dev-server\bin\webpack-dev-server.js:60:7)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
Project is running at http://localhost:8000/
webpack output is served from /
Hash: a53e5a77a5af99412018
Version: webpack 3.6.0
Time: 9641ms
                        Asset       Size  Chunks                    Chunk Names
             main.20c0790d.js    2.68 MB       0  [emitted]  [big]  main
main-20c0790d4ba4f217c2ac.css    72.7 kB       0  [emitted]         main
                 ./index.html  630 bytes          [emitted]         
 [262] ./node_modules/_antd@2.13.4@antd/lib/message/style/index.js 75 bytes {0} [built]
 [399] multi ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000 ./src/index.js 40 bytes {0} [built]
 [400] ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000 7.24 kB {0} [built]
 [401] ./node_modules/_url@0.11.0@url/url.js 23.1 kB {0} [built]
 [407] ./node_modules/_strip-ansi@3.0.1@strip-ansi/index.js 161 bytes {0} [built]
 [409] ./node_modules/_loglevel@1.5.0@loglevel/lib/loglevel.js 8.53 kB {0} [built]
 [410] ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client/socket.js 1.05 kB {0} [built]
 [441] ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client/overlay.js 3.67 kB {0} [built]
 [446] ./node_modules/webpack/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
 [448] (webpack)/hot/emitter.js 89 bytes {0} [built]
 [450] ./src/index.js 1.11 kB {0} [built]
 [682] ./node_modules/_dva-loading@1.0.2@dva-loading/lib/index.js 3.71 kB {0} [built]
 [683] ./node_modules/_babel-polyfill@6.26.0@babel-polyfill/lib/index.js 833 bytes {0} [built]
 [885] ./src/models/app.js 5.84 kB {0} [built]
 [917] ./src/router.js 2.73 kB {0} [built]
    + 970 hidden modules

ERROR in ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/main.js
Module not found: Error: Can't resolve 'json3' in 'D:\project\build-a-react-boilerplate-from-beginning-master\node_modules\_sockjs-client@1.1.4@sockjs-client\lib'
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/main.js 7:12-28
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/entry.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client/socket.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000
 @ multi ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000 ./src/index.js

ERROR in ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/iframe-bootstrap.js
Module not found: Error: Can't resolve 'json3' in 'D:\project\build-a-react-boilerplate-from-beginning-master\node_modules\_sockjs-client@1.1.4@sockjs-client\lib'
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/iframe-bootstrap.js 5:12-28
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/main.js
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/entry.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client/socket.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000
 @ multi ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000 ./src/index.js

ERROR in ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/facade.js
Module not found: Error: Can't resolve 'json3' in 'D:\project\build-a-react-boilerplate-from-beginning-master\node_modules\_sockjs-client@1.1.4@sockjs-client\lib'
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/facade.js 3:12-28
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/iframe-bootstrap.js
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/main.js
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/entry.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client/socket.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000
 @ multi ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000 ./src/index.js

ERROR in ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/info-iframe-receiver.js
Module not found: Error: Can't resolve 'json3' in 'D:\project\build-a-react-boilerplate-from-beginning-master\node_modules\_sockjs-client@1.1.4@sockjs-client\lib'
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/info-iframe-receiver.js 5:12-28
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/iframe-bootstrap.js
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/main.js
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/entry.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client/socket.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000
 @ multi ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000 ./src/index.js

ERROR in ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/info-ajax.js
Module not found: Error: Can't resolve 'json3' in 'D:\project\build-a-react-boilerplate-from-beginning-master\node_modules\_sockjs-client@1.1.4@sockjs-client\lib'
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/info-ajax.js 5:12-28
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/info-receiver.js
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/main.js
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/entry.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client/socket.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000
 @ multi ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000 ./src/index.js

ERROR in ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/info-iframe.js
Module not found: Error: Can't resolve 'json3' in 'D:\project\build-a-react-boilerplate-from-beginning-master\node_modules\_sockjs-client@1.1.4@sockjs-client\lib'
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/info-iframe.js 5:12-28
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/info-receiver.js
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/main.js
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/entry.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client/socket.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000
 @ multi ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000 ./src/index.js

ERROR in ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/transport/iframe.js
Module not found: Error: Can't resolve 'json3' in 'D:\project\build-a-react-boilerplate-from-beginning-master\node_modules\_sockjs-client@1.1.4@sockjs-client\lib\transport'
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/transport/iframe.js 12:12-28
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/transport/lib/iframe-wrap.js
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/transport-list.js
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/entry.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client/socket.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000
 @ multi ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000 ./src/index.js

ERROR in ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/utils/iframe.js
Module not found: Error: Can't resolve 'json3' in 'D:\project\build-a-react-boilerplate-from-beginning-master\node_modules\_sockjs-client@1.1.4@sockjs-client\lib\utils'
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/utils/iframe.js 6:12-28
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/transport/receiver/jsonp.js
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/transport/jsonp-polling.js
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/transport-list.js
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/entry.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client/socket.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000
 @ multi ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000 ./src/index.js

ERROR in ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/utils/escape.js
Module not found: Error: Can't resolve 'json3' in 'D:\project\build-a-react-boilerplate-from-beginning-master\node_modules\_sockjs-client@1.1.4@sockjs-client\lib\utils'
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/utils/escape.js 3:12-28
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/main.js
 @ ./node_modules/_sockjs-client@1.1.4@sockjs-client/lib/entry.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client/socket.js
 @ ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000
 @ multi ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000 ./src/index.js

ERROR in ./node_modules/_react-redux@5.0.6@react-redux/es/connect/mapDispatchToProps.js
Module not found: Error: Can't resolve 'redux' in 'D:\project\build-a-react-boilerplate-from-beginning-master\node_modules\_react-redux@5.0.6@react-redux\es\connect'
 @ ./node_modules/_react-redux@5.0.6@react-redux/es/connect/mapDispatchToProps.js 13:13-29
 @ ./node_modules/_react-redux@5.0.6@react-redux/es/connect/connect.js
 @ ./node_modules/_react-redux@5.0.6@react-redux/es/index.js
 @ ./node_modules/_dva@2.0.3@dva/index.js
 @ ./src/index.js
 @ multi ./node_modules/_webpack-dev-server@2.9.1@webpack-dev-server/client?http://localhost:8000 ./src/index.js
Child html-webpack-plugin for "index.html":
     1 asset
       [0] (webpack)/buildin/amd-options.js 82 bytes {0} [built]
       [1] ./node_modules/_html-webpack-plugin@2.30.1@html-webpack-plugin/lib/loader.js!./src/entry.ejs 1.23 kB {0} [built]
       [2] ./node_modules/_lodash@4.17.4@lodash/lodash.js 478 kB {0} [built]
       [3] (webpack)/buildin/global.js 823 bytes {0} [built]
       [4] (webpack)/buildin/module.js 521 bytes {0} [built]
Child extract-text-webpack-plugin node_modules/_extract-text-webpack-plugin@3.0.1@extract-text-webpack-plugin/dist node_modules/_css-loader@0.28.7@css-loader/index.js??ref--3-2!node_modules/_less-loader@4.0.5@less-loader/dist/cjs.js??ref--3-3!src/routes/app.less:
       [0] ./node_modules/_css-loader@0.28.7@css-loader?{"importLoaders":1,"sourceMap":true,"modules":true,"localIdentName":"[local]___[hash:base64:5]"}!./node_modules/_less-loader@4.0.5@less-loader/dist/cjs.js?{"sourceMap":true,"modifyVars":{}}!./src/routes/app.less 10.1 kB {0} [built]
       [1] ./node_modules/_css-loader@0.28.7@css-loader/lib/css-base.js 2.28 kB {0} [built]
Child extract-text-webpack-plugin node_modules/_extract-text-webpack-plugin@3.0.1@extract-text-webpack-plugin/dist node_modules/_css-loader@0.28.7@css-loader/index.js??ref--3-2!node_modules/_less-loader@4.0.5@less-loader/dist/cjs.js??ref--3-3!node_modules/_antd@2.13.4@antd/lib/style/index.less:
       [0] ./node_modules/_css-loader@0.28.7@css-loader?{"importLoaders":1,"sourceMap":true,"modules":true,"localIdentName":"[local]___[hash:base64:5]"}!./node_modules/_less-loader@4.0.5@less-loader/dist/cjs.js?{"sourceMap":true,"modifyVars":{}}!./node_modules/_antd@2.13.4@antd/lib/style/index.less 180 kB {0} [built]
       [1] ./node_modules/_css-loader@0.28.7@css-loader/lib/css-base.js 2.28 kB {0} [built]
Child extract-text-webpack-plugin node_modules/_extract-text-webpack-plugin@3.0.1@extract-text-webpack-plugin/dist node_modules/_css-loader@0.28.7@css-loader/index.js??ref--3-2!node_modules/_less-loader@4.0.5@less-loader/dist/cjs.js??ref--3-3!node_modules/_antd@2.13.4@antd/lib/layout/style/index.less:
       [0] ./node_modules/_css-loader@0.28.7@css-loader?{"importLoaders":1,"sourceMap":true,"modules":true,"localIdentName":"[local]___[hash:base64:5]"}!./node_modules/_less-loader@4.0.5@less-loader/dist/cjs.js?{"sourceMap":true,"modifyVars":{}}!./node_modules/_antd@2.13.4@antd/lib/layout/style/index.less 8.28 kB {0} [built]
       [1] ./node_modules/_css-loader@0.28.7@css-loader/lib/css-base.js 2.28 kB {0} [built]
Child extract-text-webpack-plugin node_modules/_extract-text-webpack-plugin@3.0.1@extract-text-webpack-plugin/dist node_modules/_css-loader@0.28.7@css-loader/index.js??ref--3-2!node_modules/_less-loader@4.0.5@less-loader/dist/cjs.js??ref--3-3!node_modules/_antd@2.13.4@antd/lib/message/style/index.less:
       [0] ./node_modules/_css-loader@0.28.7@css-loader?{"importLoaders":1,"sourceMap":true,"modules":true,"localIdentName":"[local]___[hash:base64:5]"}!./node_modules/_less-loader@4.0.5@less-loader/dist/cjs.js?{"sourceMap":true,"modifyVars":{}}!./node_modules/_antd@2.13.4@antd/lib/message/style/index.less 6.01 kB {0} [built]
       [1] ./node_modules/_css-loader@0.28.7@css-loader/lib/css-base.js 2.28 kB {0} [built]
Child extract-text-webpack-plugin node_modules/_extract-text-webpack-plugin@3.0.1@extract-text-webpack-plugin/dist node_modules/_css-loader@0.28.7@css-loader/index.js??ref--3-2!node_modules/_less-loader@4.0.5@less-loader/dist/cjs.js??ref--3-3!node_modules/_antd@2.13.4@antd/lib/tooltip/style/index.less:
       [0] ./node_modules/_css-loader@0.28.7@css-loader?{"importLoaders":1,"sourceMap":true,"modules":true,"localIdentName":"[local]___[hash:base64:5]"}!./node_modules/_less-loader@4.0.5@less-loader/dist/cjs.js?{"sourceMap":true,"modifyVars":{}}!./node_modules/_antd@2.13.4@antd/lib/tooltip/style/index.less 12.9 kB {0} [built]
       [1] ./node_modules/_css-loader@0.28.7@css-loader/lib/css-base.js 2.28 kB {0} [built]
Child extract-text-webpack-plugin node_modules/_extract-text-webpack-plugin@3.0.1@extract-text-webpack-plugin/dist node_modules/_css-loader@0.28.7@css-loader/index.js??ref--3-2!node_modules/_less-loader@4.0.5@less-loader/dist/cjs.js??ref--3-3!node_modules/_antd@2.13.4@antd/lib/menu/style/index.less:
       [0] ./node_modules/_css-loader@0.28.7@css-loader?{"importLoaders":1,"sourceMap":true,"modules":true,"localIdentName":"[local]___[hash:base64:5]"}!./node_modules/_less-loader@4.0.5@less-loader/dist/cjs.js?{"sourceMap":true,"modifyVars":{}}!./node_modules/_antd@2.13.4@antd/lib/menu/style/index.less 51 kB {0} [built]
       [1] ./node_modules/_css-loader@0.28.7@css-loader/lib/css-base.js 2.28 kB {0} [built]
webpack: Failed to compile.
